# Generated by Django 6.0.3 on 2026-03-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер эпизода')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название эпизода')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Длительность в минутах', verbose_name='Длительность')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10, verbose_name='Качество')),
                ('has_subtitles', models.BooleanField(default=False, verbose_name='Есть субтитры')),
                ('subtitle_languages', models.CharField(blank=True, help_text='Языки субтитров через запятую', max_length=100, verbose_name='Языки субтитров')),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Эпизод',
                'verbose_name_plural': 'Эпизоды',
                'ordering': ['season', 'number'],
            },
        ),
        migrations.CreateModel(
            name='VoiceActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название озвучки')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Озвучка',
                'verbose_name_plural': 'Озвучки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_type', models.CharField(choices=[('anitype', 'Anitype'), ('kodik', 'Kodik'), ('alloha', 'Alloha'), ('custom', 'Custom')], max_length=20, verbose_name='Тип плеера')),
                ('url', models.URLField(verbose_name='URL источника')),
                ('iframe_url', models.URLField(blank=True, verbose_name='URL iframe')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('4K', '4K')], default='720p', max_length=10, verbose_name='Качество')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_sources', to='episodes.episode', verbose_name='Эпизод')),
            ],
            options={
                'verbose_name': 'Источник плеера',
                'verbose_name_plural': 'Источники плеера',
                'ordering': ['-is_default', 'player_type'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='Номер сезона')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название сезона')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='anime.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['number'],
                'unique_together': {('anime', 'number')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='episodes.season', verbose_name='Сезон'),
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('ja', '日本語')], max_length=10, verbose_name='Язык')),
                ('file', models.FileField(upload_to='subtitles/', verbose_name='Файл субтитров')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='episodes.episode', verbose_name='Эпизод')),
            ],
            options={
                'verbose_name': 'Субтитр',
                'verbose_name_plural': 'Субтитры',
                'ordering': ['language'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='voice_actors',
            field=models.ManyToManyField(blank=True, related_name='episodes', to='episodes.voiceactor', verbose_name='Озвучки'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'number'], name='episodes_ep_season__afbbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-released_at'], name='episodes_ep_release_2ddd92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number')},
        ),
    ]
