# Generated by Django 6.0.3 on 2026-03-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersource',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/episodes/', verbose_name='Видеофайл'),
        ),
        migrations.AddField(
            model_name='playersource',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='URL видеофайла'),
        ),
        migrations.AlterField(
            model_name='playersource',
            name='player_type',
            field=models.CharField(choices=[('anitype', 'Anitype'), ('kodik', 'Kodik'), ('alloha', 'Alloha'), ('video', 'Прямое видео (Plyr)'), ('custom', 'Custom iframe')], max_length=20, verbose_name='Тип плеера'),
        ),
        migrations.AlterField(
            model_name='playersource',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL источника'),
        ),
    ]
