# Generated by Django 6.0.3 on 2026-03-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_playersource_video_file_playersource_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='has_subtitles',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='subtitle_languages',
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
    ]
