# Generated by Django 6.0.3 on 2026-03-10 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(blank=True, help_text='Время заметки в секундах', null=True, verbose_name='Время заметки')),
                ('content', models.TextField(verbose_name='Текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='episodes.episode', verbose_name='Эпизод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='player_user_user_id_6a2678_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('completed', models.BooleanField(default=False, verbose_name='Просмотрено до конца')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='episodes.episode', verbose_name='Эпизод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'История просмотров',
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user', '-watched_at'], name='player_watc_user_id_b2a19f_idx')],
                'unique_together': {('user', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='WatchMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(help_text='Время момента в секундах', verbose_name='Время момента')),
                ('moment_type', models.CharField(choices=[('funny', 'Смешной момент'), ('epic', 'Эпичный момент'), ('important', 'Важный момент'), ('opening', 'Открывашка'), ('ending', 'Заставка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип момента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='episodes.episode', verbose_name='Эпизод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_moments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Момент',
                'verbose_name_plural': 'Моменты',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['episode', 'timestamp'], name='player_watc_episode_263a82_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.PositiveIntegerField(default=0, help_text='Текущая позиция в секундах', verbose_name='Текущее время')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Общая длительность в секундах', verbose_name='Длительность')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to='episodes.episode', verbose_name='Эпизод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс просмотра',
                'verbose_name_plural': 'Прогресс просмотров',
                'ordering': ['-last_watched'],
                'indexes': [models.Index(fields=['user', '-last_watched'], name='player_watc_user_id_e2428c_idx')],
                'unique_together': {('user', 'episode')},
            },
        ),
    ]
