# Generated by Django 6.0.3 on 2026-03-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usernote',
            name='player_user_user_id_6a2678_idx',
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='watchhistory',
            name='player_watc_user_id_b2a19f_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchmoment',
            name='player_watc_episode_263a82_idx',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchmoment',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='watchmoment',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserNote',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
        migrations.DeleteModel(
            name='WatchMoment',
        ),
    ]
