# Generated by Django 6.0.3 on 2026-03-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_usernote_player_user_user_id_6a2678_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='watchprogress',
            name='player_watc_user_id_e2428c_idx',
        ),
        migrations.DeleteModel(
            name='WatchProgress',
        ),
    ]
