# Generated by Django 6.0.3 on 2026-03-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Название (русское)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Название (английское)')),
                ('title_original', models.CharField(blank=True, max_length=300, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='anime/posters/', verbose_name='Постер')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='anime/covers/', verbose_name='Обложка')),
                ('status', models.CharField(choices=[('ongoing', 'Онгоинг'), ('completed', 'Завершено'), ('announced', 'Анонсировано'), ('hiatus', 'На паузе')], default='ongoing', max_length=20, verbose_name='Статус')),
                ('rating', models.CharField(choices=[('g', 'G - Для любого возраста'), ('pg', 'PG - Детям 6+'), ('pg13', 'PG-13 - Подросткам 13+'), ('r17', 'R-17 - 17+'), ('r', 'R - 18+'), ('rx', 'RX - Хентай')], default='pg13', max_length=10, verbose_name='Рейтинг')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Оценка')),
                ('episodes_count', models.PositiveIntegerField(default=0, verbose_name='Количество эпизодов')),
                ('duration', models.PositiveIntegerField(default=0, help_text='Длительность эпизода в минутах', verbose_name='Длительность эпизода')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выхода')),
                ('released_at', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='В закладках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('genres', models.ManyToManyField(blank=True, related_name='anime', to='anime.genre', verbose_name='Жанры')),
                ('studios', models.ManyToManyField(blank=True, related_name='anime', to='anime.studio', verbose_name='Студии')),
                ('tags', models.ManyToManyField(blank=True, related_name='anime', to='anime.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['-year', '-title_ru'],
                'indexes': [models.Index(fields=['-year', '-title_ru'], name='anime_anime_year_8672f6_idx'), models.Index(fields=['status'], name='anime_anime_status_6458e9_idx'), models.Index(fields=['-score'], name='anime_anime_score_b7efa8_idx'), models.Index(fields=['-views_count'], name='anime_anime_views_c_09a363_idx')],
            },
        ),
    ]
