# Generated by Django 6.0.3 on 2026-03-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='cover',
        ),
    ]
