# Generated by Django 6.0.3 on 2026-03-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='studios',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
