# Generated by Django 6.0.3 on 2026-03-10 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anime', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('ongoing', 'Онгоинг'), ('completed', 'Завершено'), ('announced', 'Анонсировано'), ('hiatus', 'На паузе')], max_length=20, verbose_name='Статус')),
                ('min_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Мин. рейтинг')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Год от')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Год до')),
                ('sort_by', models.CharField(choices=[('-year', 'По году (новые)'), ('year', 'По году (старые)'), ('-score', 'По рейтингу'), ('-views_count', 'По просмотрам'), ('-title_ru', 'По названию (А-Я)'), ('title_ru', 'По названию (Я-А)'), ('-released_at', 'По дате выхода')], default='-year', max_length=30, verbose_name='Сортировка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_presets', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('genres', models.ManyToManyField(blank=True, related_name='filter_presets', to='anime.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Пресет фильтра',
                'verbose_name_plural': 'Пресеты фильтров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название подборки')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Обложка')),
                ('collection_type', models.CharField(choices=[('manual', 'Ручная'), ('auto', 'Автоматическая'), ('trending', 'Сейчас смотрят'), ('popular', 'Популярное'), ('top_rated', 'Лучшие по рейтингу')], default='manual', max_length=20, verbose_name='Тип')),
                ('filter_min_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Мин. рейтинг')),
                ('filter_year_from', models.IntegerField(blank=True, null=True, verbose_name='Год от')),
                ('filter_year_to', models.IntegerField(blank=True, null=True, verbose_name='Год до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Приоритет отображения', verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('animes', models.ManyToManyField(blank=True, related_name='collections', to='anime.anime', verbose_name='Аниме')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('filter_genres', models.ManyToManyField(blank=True, related_name='collections', to='anime.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Подборка',
                'verbose_name_plural': 'Подборки',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['collection_type', 'is_active'], name='catalog_col_collect_ccf12f_idx'), models.Index(fields=['-priority', 'is_active'], name='catalog_col_priorit_37e71d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, verbose_name='Поисковый запрос')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Количество результатов')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поисковый запрос',
                'verbose_name_plural': 'Поисковые запросы',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['-searched_at'], name='catalog_sea_searche_6fae1b_idx'), models.Index(fields=['query'], name='catalog_sea_query_c57f81_idx')],
            },
        ),
    ]
