# Generated by Django 6.0.3 on 2026-03-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animefilterpreset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='animefilterpreset',
            name='genres',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='catalog_sea_searche_6fae1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchquery',
            name='catalog_sea_query_c57f81_idx',
        ),
        migrations.DeleteModel(
            name='AnimeFilterPreset',
        ),
        migrations.DeleteModel(
            name='SearchQuery',
        ),
    ]
