# Generated by Django 6.0.3 on 2026-03-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_animefilterpreset_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collection',
            name='catalog_col_collect_ccf12f_idx',
        ),
        migrations.RemoveIndex(
            model_name='collection',
            name='catalog_col_priorit_37e71d_idx',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
